# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reklamacije.net Admin
description: Stranice namjenjene za administratore Alaveteli portala.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://admin.reklamacije.net" # the base hostname & protocol for your site
github_repo: reklamacijenet-admin # the GitHub repo name for your project
github_username: codeforcroatia
portal:
  name: Reklamacije.net
  url: "http://reklamacije.net"
  app: Alaveteli
  type: "Zaštita prava potrošača"
  domain: reklamacije.net

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: codeforcroatia

# custom social link Facebook
social_fb_username: programirajzahrvatsku

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow; violet (custom).
theme_color: violet

# Build settings
markdown: kramdown

# Site analytics
analytics:
  provider: google
  google:
    id: UA-2846894-3
